# Generated by Django 5.0.2 on 2024-03-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='feedbac',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='feedBack',
            new_name='feedback',
        ),
    ]
