# Generated by Django 5.0.2 on 2024-03-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_feedbac_form_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='feedback',
        ),
        migrations.AlterField(
            model_name='form',
            name='feedback',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='API.product'),
        ),
    ]
